# -*- coding: utf-8 -*-
"""Py4DS_Lab2_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1VCpQm0KOVSx1dGPiyGbp4zI-Atzsxu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

data = pd.read_csv('Datasets/Py4DS_Lab2/xAPI-Edu-Data.csv')
data

for i in range(0,data.shape[1]):
  print(data.iloc[:,i].value_counts())
  print('*'*30)

for i in range(0,data.shape[1]):
  print(data.iloc[:,i].describe())
  print("*"*30)

sns.pairplot(data=data, hue = 'Class')
print('Hoc sinh xep hang L: raisedhands, visitedresource, annoucementsViews, Discussion deu thap')
print('Hoc sinh xep hang M: raisedhands, visitedresource, annoucementsViews, Discussion dong deu')
print('Hoc sinh xep hang H: ')

plt.figure(figsize=(14,14))
sns.heatmap(data.corr(),cmap='YlGnBu',annot=True)
print('Raisehands/VisitedResource, Raisehands/AnnouncementsViews tuong quan ti le thuan')

P_static = sns.countplot(x='Class',data=data)
print('Du lieu phan bo kha dong deu')

plt.figure(figsize=(20,14))
data.raisedhands.value_counts().sort_index().plot.bar()
print('rat nhieu hoc sinh gio tay 10, 70, 80 lan')

plt.figure(figsize = (10,10))
Raise_hand = sns.boxplot(x="Class",y="raisedhands",data=data)
plt.show()
print('Medium co phan bo dong deu')
print('Low co phan bo lech duoi voi rat nhieu outlayer phia tren')
print('High co phan bo dong deu voi rat nhieu outlayer phia duoi')

FacetGrid = sns.FacetGrid(data,hue='Class')
FacetGrid.map(sns.kdeplot,"raisedhands",shade=True)
FacetGrid.set(xlim = (0,data.raisedhands.max()))
print('do thi phan phoi co dung kde de lam muot hinh')

data.groupby(['ParentschoolSatisfaction'])['Class'].value_counts()
print('Class L thi thuong Bad')
print('Class M thi Good = 2 lan Bad')
print('Class H thi thuong Good')

pd.crosstab(data['Class'],data['ParentschoolSatisfaction'])

sns.countplot(x="ParentschoolSatisfaction",data=data, hue = "Class")

labels = data.ParentschoolSatisfaction.value_counts()
print(labels)
colors = ["blue","green"]
explode = [0,0]
sizes = data.ParentschoolSatisfaction.value_counts().values
print(sizes)
plt.pie(sizes, explode=explode,labels=labels, colors = colors)
plt.show()
print('do thi hinh cau the hien ti le phan tram cua good va bad')

