# -*- coding: utf-8 -*-
"""Py4DS_Lab2_Ex4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vh0AaLp8dWCdAyLmFksmJBGdDxVYUvEu

#**EDA** (Explotary Data Analysis)

#**Read and view file**
"""

import numpy as np
import pandas as pd

df = pd.read_csv(r'./HappinessReport2020.csv')
df.head()

"""#**Summary-statistic**"""

df.describe()

"""#**1. Pie plot**"""

print(df.groupby('Regional indicator')['Logged GDP per capita'].sum())
df.groupby('Regional indicator')['Logged GDP per capita'].sum().plot.pie(figsize = (10, 10))

"""**Giải thích chi tiết (biểu đồ):**

- Nhìn vào biểu đồ, ta thấy rằng tổng GDP ở các khu vực sub-saharan of africa (Vùng hạ của sa mạc Sahara) và Western Europe là các khu vực chiếm trọng số lớn hơn hẳn các vùng còn lại

- Tổng GDP của 3 vùng North America and ANZ, Southeast Asia và South Asia lại chiếm tỷ lệ rất ít.
- Tuy nhiên, tổng GDP này không thể phản ánh mức sống của các khu vực bởi một số khu vực có rất ít quốc gia như North America and ANZ, do đó khi dùng biểu đồ tròn cho GDP ta nên xét cả 2 hàm là sum() và mean().
"""

print(df.groupby('Regional indicator')['Logged GDP per capita'].mean())
df.groupby('Regional indicator')['Logged GDP per capita'].mean().plot.pie(figsize = (10, 10))

"""**Giải thích chi tiết (biểu đồ):**


Khi dùng mean
- Trường hợp tỉ lệ nghịch giữa "Tổng GDP" và "Trung bình GDP":
  - Khu vực North America and ANZ dù có "Tổng GDP" thấp nhất nhưng có "Trung bình GDP" cao nhất trong tất cả các khu vực. 

    Tương tự khu vực North America and ANZ thì khu vực East Asia cũng có "Tổng GDP" thấp nhưng có "Trung bình GDP" cao.

  - Còn khu vực Sub-Saharan of Africa ban đầu có tổng GDP cao nhất nhưng khi tính về trung bình GDP thì đây là khu vực có mức thấp nhất.

- Trường hợp tỉ lệ thuận giữa "Tổng GDP" và "Trung bình GDP":
  - Khu vực Western Europe  có "Tổng GDP" và "Trung bình GDP" đều cao.

Conclusion: Tổng GDP sẽ không phản ánh được mức sống tại mỗi quốc gia, phải dùng  Trung bình GDP để biết rõ mức sống này. Nhìn vào số liệu và biểu đồ ta có thể thấy 3 khu vực có mức sống cao (theo thứ tự giảm dần) là North America and ANZ , Western Europe và East Asia. Còn Sub-Saharan Africa là khu vực có mức sống thấp nhất.

#**2. Box-plot. Biểu đồ hình hộp.**
"""

df['Healthy life expectancy'].plot(kind = 'box', figsize = (4, 8));
print(df['Healthy life expectancy'].describe())

"""* Nhìn vào kết quả trong cú pháp dataframe.describe(), ta chỉ cần quan tâm các giá trị sau

                      min       45.200001
                      25%       58.961712     (Q1)
                      50%       66.305145     (Q2)
                      75%       69.289192     (Q3)
                      max       76.804581

* Theo đó, hình hộp chữ nhật trong boxplot sẽ giới hạn bởi các đường Q1 = 58.96 và Q3 = 69.289 và đường phân đôi hình chữ nhật này chính là Q2 (trung vị) = 66.305.
* Khoảng giá trị [Q1, Q3] (trung tâm của boxplot) cho biết có đến 50% dữ liệu được phân bố tập trung trong khoảng này.

* Từ các giá trị Q1, Q2, Q3 cho thấy dữ liệu trong biến Healthy life expectancy đang lệch, cụ thể vì Q2 gần Q3 rất nhiều so với Q1 nên dữ liệu có trung vị cao hơn so với trung bình của biến Healthy life expectancy. Ngoài ra, ta dễ dàng tính được

                          IQR = Q3 - Q1 = 10.327

    từ đó tính được

                          a = max(45.20, 58.961 - 1.5*IQR) = 45.2
                          b = min(76.804, 76.289 + 1.5*IQR) = 76.804

    như vậy dữ liệu trong biến Healthy life expectancy không có outliers.

#**3. Biểu đồ cột - histogram.**
"""

df['Logged GDP per capita'].hist(bins = 10)

"""- Trục tung đang là đếm số dữ liệu rơi vào một cột nào đó, ví dụ có 4 dữ liệu nằm trong khoảng [3, 7], 12 dữ liệu trong khoảng (7, 8], ... và chỉ có 7 dữ liệu trên mức 10.8. Điều này có nghĩa là trong 153 quốc gia đang được khảo sát thì chỉ có 4 quốc gia có mức thu nhập Logged GDP per capita dưới 7, ..., và 7 quốc gia có thu nhập rất cao (trên 10.8).

- Hầu hết dữ liệu phân bố tập trung ở khoảng [7, 9.5] phản ánh rằng có đến gần 2/3 trong tổng số các quốc gia được khảo sát có thu nhập dưới mức.

#**4. Heat-map. Biểu đồ nhiệt.**
"""

import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, figsize = (10, 10))
sns.heatmap(df.corr(), linewidths = 2, ax = ax)
